// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var color;
    return color = ImageAnalyzer('img/p-icons.jpg', function(bgcolor, primaryColor, secondaryColor, detailColor) {
      $('body').css('background-color', 'rgb(' + bgcolor + ')');
      $('h1,h2').css('color', 'rgb(' + primaryColor + ')');
      $('a').css('color', 'rgb(' + secondaryColor + ')');
      $('.box').css('border-color','rgb(' + primaryColor + ')')
      return $('p').css('color', 'rgb(' + detailColor + ')');
    });
  });

}).call(this);
